services:

  timesheet-consumer:
    image: "${APP_TIMESHEET_CONSUMER_IMAGE_NAME}:${APP_TIMESHEET_CONSUMER_IMAGE_VERSION}"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${APP_MESSAGE_BROKER_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${APP_MESSAGE_BROKER_PASSWORD}
      - RABBITMQ_HOST=${APP_MESSAGE_BROKER_HOST}
      - RABBITMQ_PORT=${APP_MESSAGE_BROKER_PORT}
      - TIMESHEET_URL=${APP_TIMESHEET_URL}

networks:
  default:
    name: ${APP_PROXY_NETWORK}
    external: true
