services:

  email-db:
    image: "${APP_EMAIL_DB_IMAGE_NAME}:${APP_EMAIL_DB_IMAGE_VERSION}"
    environment:
      - POSTGRES_USER=${APP_EMAIL_DB_USERNAME}
      - POSTGRES_PASSWORD=${APP_EMAIL_DB_PASSWORD}
      - POSTGRES_DB=${APP_EMAIL_DB_NAME}
      - PGDATA=/var/lib/postgresql/data/external
    volumes:
      - "${APP_EMAIL_DB_DATA_PATH}:/var/lib/postgresql/data/external"
    ports:
      - 5435:5432

networks:
  default:
    name: ${APP_PROXY_NETWORK}
    external: true
